import React from 'react';
import './PrivacyPolicy.scss'
import {
    Container, Form, Row, Col, InputGroup,
} from 'react-bootstrap';
import { Link } from 'react-router-dom';


const PrivacyPolicy = () => {
    return (
        <Container fluid className="privacyPolicy-container">
            <Row>
                <div className='privacyPolicyimage'>

                </div>
            </Row>
            <Row>
                <Col className="privacyPolicy-text">
                    <div className='PrivacyPolicyPage'>
                        <div id="privacy-policy" className="PrivacyPolicy">

                            <strong>Privacy Policy</strong>
                            <br />
                            <p>Last updated: January 3, 2023</p>
                            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of your information. It describes your privacy rights and how the law protects you.</p>
                            <p>The website collects personal data to provide and improve delivery of communication to its users. By using this service, you agree to the collection and use of your information in accordance with this policy.</p>
                            <strong>Interpretation and Definitions</strong>
                            <br/>
                            <br/>
                            <b>Interpretation</b>
                            <br/>
                            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                            <b>Definitions</b>
                            <br/>
                            <p>For the purposes of this Privacy Policy:</p>
                            <ul>
                                <li>
                                    <p><b>Account</b> means a unique account created for You (Jain Student or Alumni) to access our Service or parts of our Service.</p>
                                </li>
                                <li>
                                    <p><b>Organization</b> (referred to as either &quot;the Organization&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to JJC USA</p>
                                </li>
                                <li>
                                    <p><b>Parent Organization</b> JJC USA is part of Jain Jagruti Centre Central Board and Charitable Trust</p>
                                </li>
                                <li>
                                    <p><b>Cookies</b>are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                                </li>
                                <li>
                                    <p><b>Country</b> refers to: United States</p>
                                </li>
                                <li>
                                    <p><b>Device</b> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
                                </li>
                                <li>
                                    <p><b>Personal Data</b> is any information that relates to an identified or identifiable individual.</p>
                                </li>
                                <li>
                                    <p><b>Service</b> refers to the Website.</p>
                                </li>
                                <li>
                                    <p><b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Organization. It refers to third-party companies or individuals employed by the Organization to facilitate the Service, to provide the Service on behalf of the Organization, to perform services related to the Service or to assist the Organization in analyzing how the Service is used.</p>
                                </li>
                                <li>
                                    <p><b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                                </li>
                                <li>
                                    <p><b>Website</b> refers to JJC USA, accessible from&nbsp;http://www.jjcusa.org/</p>
                                </li>
                                <li>
                                    <p><b>You</b> means the individual accessing or using the Service, as applicable.</p>
                                </li>
                            </ul>
                            <p><br /></p>
                            <strong>Collecting and Using Your Personal Data</strong>
                            <br/>
                            <br/>
                            <b>Types of Data Collected</b>
                            <br/>
                            <br/>
                            <h6><b>Personal Data</b></h6>
                            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                            <ul>
                                <li>
                                    <p>Email address</p>
                                </li>
                                <li>
                                    <p>First name and Last name</p>
                                </li>
                                <li>
                                    <p>Current Status (Student / Alumni)</p>
                                </li>
                                <li>
                                    <p>Linked In URL</p>
                                </li>
                                <li>
                                    <p>Phone number</p>
                                </li>
                                <li>
                                    <p>University Name, Start Year, End Year</p>
                                </li>
                                <li>
                                    <p>City, State, Province, ZIP/Postal code</p>
                                </li>
                                <li>
                                    <p>Job Title, Location, Start Year</p>
                                </li>
                                <li>
                                    <p>Community Proof Document</p>
                                </li>
                                <li>
                                    <p>Profile Picture</p>
                                </li>
                                <li>
                                    <p>Loan Information&nbsp;</p>
                                </li>
                                <li>
                                    <p>Usage Data</p>
                                </li>
                            </ul>
                            <p><br /></p>
                            <b>Data Collection</b>
                            <p>Website may collect data based on various data gathering methods listed below, but not limited to:</p>
                            <ul>
                                <li>
                                    <p>Registration Forms</p>
                                </li>
                                <li>
                                    <p>Surveys</p>
                                </li>
                                <li>
                                    <p>Newsletter Signups</p>
                                </li>
                                <li>
                                    <p>Usage Data</p>
                                </li>
                            </ul>
                            <p><br /></p>
                            <b>Usage Data</b>
                            <br/>
                            <br/>
                            <p>Usage Data is collected automatically when using the Service.</p>
                            <p>Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                            <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
                            <b>Tracking Technologies and Cookies</b>
                            <br/>
                            <br/>
                            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                            <ul>
                                <li>
                                    <p><b>Cookies or Browser Cookies.</b> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</p>
                                </li>
                                <li>
                                    <p><b>Flash Cookies.</b> Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read &quot;Where can I change the settings for disabling, or deleting local shared objects?&quot;&nbsp;</p>
                                </li>
                                <li>
                                    <p><b>Web Beacons.</b> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Organization, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</p>
                                </li>
                            </ul>
                            <p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the&nbsp;Privacy Policies website&nbsp;article.</p>
                            <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
                            <ul>
                                <li>
                                    <p><b>Necessary / Essential Cookies</b></p>
                                </li>
                            </ul>
                            <p>Type: Session Cookies</p>
                            <p>Administered by: Us</p>
                            <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                            <ul>
                                <li>
                                    <p><b>Cookies Policy / Notice Acceptance Cookies</b></p>
                                </li>
                            </ul>
                            <p>Type: Persistent Cookies</p>
                            <p>Administered by: Us</p>
                            <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                            <ul>
                                <li>
                                    <p><b>Functionality Cookies</b></p>
                                </li>
                            </ul>
                            <p>Type: Persistent Cookies</p>
                            <p>Administered by: Us</p>
                            <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
                            <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
                            <strong>Use of Your Personal Data</strong>
                            <p>The Organization may use Personal Data for the following purposes:</p>
                            <ul>
                                <li>
                                    <p><b>To provide and maintain our Service:</b> including to monitor the usage of our Service.</p>
                                </li>
                                <li>
                                    <p><b>To approve access to the Account:</b> to allow You access to the website according to the terms and conditions, we might access your Personal Data</p>
                                </li>
                                <li>
                                    <p><b>To manage Your Account:</b> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
                                </li>
                                <li>
                                    <p><b>To contact You:</b> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</p>
                                </li>
                                <li>
                                    <p><b>To manage Your requests:</b> To attend and manage Your requests to Us.</p>
                                </li>
                                <li>
                                    <p><b>For other purposes:</b> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our newsletters and to evaluate and improve our Service, marketing and your experience.</p>
                                </li>
                            </ul>
                            <p>We may share Your personal information in the following situations:</p>
                            <ul>
                                <li>
                                    <p><b>With Affiliates:</b> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent organization and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</p>
                                </li>
                                <li>
                                    <p><b>With other users:</b> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</p>
                                </li>
                                <li>
                                    <p><b>With Your consent:</b> We may disclose Your personal information for any other purpose with Your consent.</p>
                                </li>
                            </ul>
                            <strong>Retention of Your Personal Data</strong>
                            <p>The Organization will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                            <p>The Organization will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
                            <strong>Transfer of Your Personal Data</strong>
                            <p>Your information, including Personal Data, is processed at the Organization&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to &mdash; and maintained on &mdash; computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
                            <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
                            <p>The Organization will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
                            <p>Disclosure of Your Personal Data</p>
                            <b>Business Transactions</b>
                            <p>If the Organization is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
                            <b>Law enforcement</b>
                            <br/>
                            <br/>
                            <p>Under certain circumstances, the Organization may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                            <b>Other legal requirements</b>
                            <br/>
                            <br/>
                            <p>The Organization may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                            <ul>
                                <li>
                                    <p>Comply with a legal obligation</p>
                                </li>
                                <li>
                                    <p>Protect and defend the rights or property of the Organization</p>
                                </li>
                                <li>
                                    <p>Prevent or investigate possible wrongdoing in connection with the Service</p>
                                </li>
                                <li>
                                    <p>Protect the personal safety of Users of the Service or the public</p>
                                </li>
                                <li>
                                    <p>Protect against legal liability</p>
                                </li>
                            </ul>
                            <strong>Security of Your Personal Data</strong>
                            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                            <strong>Children&apos;s Privacy</strong>
                            <p>Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 18 without verification of parental consent, We take steps to remove that information from Our servers.</p>
                            <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&apos;s consent before We collect and use that information.</p>
                            <strong>Links to Other Websites</strong>
                            <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.</p>
                            <strong>Changes to this Privacy Policy</strong>
                            <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                            <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
                            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                            <strong>Contact Us</strong>
                            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                            <ul>
                                <li>
                                    <p><b>By email: jjcsausa@gmail.com</b></p>
                                </li>
                            </ul>
                        </div>

                    </div>
                </Col>
            </Row>
        </Container>

    );

}
export default PrivacyPolicy;